[package]
name = "Real-time stablecoin settlement network"

version = "1.0.0"
authors = []

[addresses]
real_time_stablecoin_settlement_network = '0x3dd840264b9e792d995c5abea0847d9e79ce929fb1c3a2c8c5ff331e8e1f9f4d'

[dev-addresses]
[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"  # Replace with a valid branch or commit hash if 'testnet' isn't valid
subdir = "aptos-move/framework/aptos-framework"
[dev-dependencies]


